on:
  push: { branches: [master] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to github registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository_owner }}/ytdlbot
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "latest,0.1"
        env:
          DOCKER_BUILDKIT: 1 # faster?
